---
services:
  ollama:
    image: ollama/ollama:0.1.37
    container_name: ollama
    volumes:
    - ./.docker_data/ollama:/root/.ollama

  ollama-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: ollama-webui
    volumes:
      - ./.docker_data/ollama-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - 8080:8080
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - WEBUI_AUTH=False
...